version: '3.1'

services:
  db:
    image: postgres:13.1
    restart: always
    ports:
    - 5432:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
