FROM node:16

WORKDIR /home/node/app

COPY api/package*.json ./

# Install nodemon for hot reload (Probably not neccessary)
# RUN npm install -g nodemon

RUN npm install

# run nodemon for hot reload
CMD ["npm", "test"]