FROM node:16

WORKDIR /home/node/app

# install app dependencies
COPY frontend/package*.json ./

RUN npm install
# RUN npm install react-scripts@3.4.1 -g --silent

# COPY . .

# start app
CMD ["npm", "start"]