CREATE TABLE IF NOT EXISTS Plane ( 
	PlaneID INTEGER NOT NULL, 
	PlaneVersion INTEGER NOT NULL,
	PRIMARY KEY (PlaneID, PlaneVersion)
); 
CREATE TABLE IF NOT EXISTS Glider (
	GliderID INTEGER NOT NULL,
	GliderVersion INTEGER NOT NULL,
	PRIMARY KEY (GliderID, GliderVersion)
);
CREATE TABLE IF NOT EXISTS FlightPath (
	FlightPathID INTEGER NOT NULL,
	PilotName CHARACTER(50) NOT NULL,
	LocationID INTEGER NOT NULL,
	AirplaneType CHARACTER(20) NOT NULL,
	PlaneID INTEGER NOT NULL,
	PlaneVersion INTEGER NOT NULL,
	GliderID INTEGER NOT NULL,
	GliderVersion INTEGER NOT NULL,
    PRIMARY KEY (FlightPathID)
	FOREIGN KEY (PlaneID) REFERENCES Plane(PlaneID),
    FOREIGN KEY (PlaneVersion) REFERENCES Plane(PlaneVersion),
    FOREIGN KEY (GliderID) REFERENCES Glider(GliderID),
    FOREIGN KEY (GliderVersion) REFERENCES Glider(GliderVersion)
);
CREATE TABLE IF NOT EXISTS Point (
	FlightPathID INTEGER NOT NULL,
	PointID INTEGER NOT NULL,
	PRIMARY KEY (FlightPathID, PointID),
	FOREIGN KEY (FlightPathID) REFERENCES FlightPath(FlightPathID)
);
CREATE TABLE IF NOT EXISTS GpsValue (
	Latitude DOUBLE NOT NULL,
	Longitude DOUBLE NOT NULL,
	Speed DOUBLE NOT NULL,
	Satellite DOUBLE NOT NULL,
	Altitude DOUBLE NOT NULL,
	Time DOUBLE NOT NULL,
	Date INTEGER NOT NULL,
	FlightPathID INTEGER NOT NULL,
	PointID INTEGER NOT NULL,
	PRIMARY KEY (FlightPathID, PointID)
	FOREIGN KEY (FlightPathID) REFERENCES FlightPath(FlightPathID)
	FOREIGN KEY (PointID) REFERENCES Point(PointID)
);
CREATE TABLE IF NOT EXISTS ImuValues (
	AccelerometerX DOUBLE NOT NULL,
	AccelerometerY DOUBLE NOT NULL,
	AccelerometerZ DOUBLE NOT NULL,
	Yaw DOUBLE NOT NULL,
	Pitch DOUBLE NOT NULL,
	Roll DOUBLE NOT NULL,
	MagnetometerX DOUBLE NOT NULL,
	MagnetometerY DOUBLE NOT NULL,
	MagnetometerZ DOUBLE NOT NULL,
	GyroscopeX DOUBLE NOT NULL,
	GyroscopeY DOUBLE NOT NULL,
	GyroscopeZ DOUBLE NOT NULL,
	FlightPathID INTEGER NOT NULL,
	PointID INTEGER NOT NULL,
	PRIMARY KEY (FlightPathID, PointID)
	FOREIGN KEY (FlightPathID) REFERENCES FlightPath(FlightPathID)
	FOREIGN KEY (PointID) REFERENCES Point(PointID)
);
CREATE TABLE IF NOT EXISTS EnvironmentalSensorData (
	Pressure DOUBLE NOT NULL,
	Humidity DOUBLE NOT NULL,
	Temperature DOUBLE NOT NULL,
    FlightPathID INTEGER NOT NULL,
	PointID INTEGER NOT NULL,
	PRIMARY KEY (FlightPathID, PointID)
	FOREIGN KEY (FlightPathID) REFERENCES FlightPath(FlightPathID)
	FOREIGN KEY (PointID) REFERENCES Point(PointID)
);
CREATE TABLE IF NOT EXISTS BatteryStatus (
	Voltage DOUBLE NOT NULL,
	Current DOUBLE NOT NULL,
    FlightPathID INTEGER NOT NULL,
	PointID INTEGER NOT NULL,
	PRIMARY KEY (FlightPathID, PointID)
	FOREIGN KEY (FlightPathID) REFERENCES FlightPath(FlightPathID)
	FOREIGN KEY (PointID) REFERENCES Point(PointID)
);
CREATE TABLE IF NOT EXISTS SystemStatus (
	Rssi DOUBLE NOT NULL,
	State DOUBLE NOT NULL
);
CREATE TABLE IF NOT EXISTS ServoData (
	Servo0 DOUBLE NOT NULL,
	Servo1 DOUBLE NOT NULL,
	Servo2 DOUBLE NOT NULL,
	Servo3 DOUBLE NOT NULL,
	Servo4 DOUBLE NOT NULL,
	Servo5 DOUBLE NOT NULL,
	Servo6 DOUBLE NOT NULL,
	Servo7 DOUBLE NOT NULL,
	Servo8 DOUBLE NOT NULL,
	Servo9 DOUBLE NOT NULL,
	Servo10 DOUBLE NOT NULL,
	Servo11 DOUBLE NOT NULL,
	Servo12 DOUBLE NOT NULL,
	Servo13 DOUBLE NOT NULL,
	Servo14 DOUBLE NOT NULL,
	Servo15 DOUBLE NOT NULL,
    FlightPathID INTEGER NOT NULL,
	PointID INTEGER NOT NULL,
	PRIMARY KEY (FlightPathID, PointID)
	FOREIGN KEY (FlightPathID) REFERENCES FlightPath(FlightPathID)
	FOREIGN KEY (PointID) REFERENCES Point(PointID)
);
